---
dhcp_interface: "eth0"
dhcp_subnet: "192.168.56.0/24"
dhcp_pool_start: "192.168.56.100"
dhcp_pool_end: "192.168.56.200"
dhcp_router: "192.168.56.1"
dhcp_dns_server: "192.168.56.10" # IP do nosso servidor Samba AD/BIND9
dhcp_domain: "empresa.local"
